# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: mG4.tv API
  description: |
    The api used by mG4 to manage streaming video content and metadata
  version: "1.0.0"
# the domain of the service
host: api.mg4.tv
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /users/{username}:
    get:
      summary: User profile information
      description: |
        Placeholder text
      parameters:
        - name: username
          in: path
          required: true
          type: string
          format: UTF-8
      tags:
        - Users
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      code:
        type: number
        format: number
        description: A serialized representation of the HTTP error code returned in the header
      message:
        type: string
        description: A human-readable message describing the reason for the error
      fields:
        type: array
        items: 
          type: string
        description: A list of fields that the API believes is causing the error
